// ============================================
// 🤖 自动生成的全局类型声明
// 生成时间: 2026-06-12T09:30:24.091Z
// ============================================

import type { Component, ComponentPublicInstance } from 'vue'

export * from '../dist/components/index.js'
export {}

import ZhuiPlus from '../dist/components/index.js'
export default ZhuiPlus

// ===== 全局类型扩展 =====

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
 ZhAichat: typeof import('../dist/components/index.d.ts')['ZhAichat']
 ZhBadge: typeof import('../dist/components/index.d.ts')['ZhBadge']
 ZhButtonGroup: typeof import('../dist/components/index.d.ts')['ZhButtonGroup']
 ZhButton: typeof import('../dist/components/index.d.ts')['ZhButton']
 ZhBarchart: typeof import('../dist/components/index.d.ts')['ZhBarchart']
 ZhBasechart: typeof import('../dist/components/index.d.ts')['ZhBasechart']
 ZhCirclechart: typeof import('../dist/components/index.d.ts')['ZhCirclechart']
 ZhLinebarchart: typeof import('../dist/components/index.d.ts')['ZhLinebarchart']
 ZhLinechart: typeof import('../dist/components/index.d.ts')['ZhLinechart']
 ZhMapchart: typeof import('../dist/components/index.d.ts')['ZhMapchart']
 ZhPictorialbar: typeof import('../dist/components/index.d.ts')['ZhPictorialbar']
 ZhPiechart: typeof import('../dist/components/index.d.ts')['ZhPiechart']
 ZhRadarchart: typeof import('../dist/components/index.d.ts')['ZhRadarchart']
 ZhScatterchart: typeof import('../dist/components/index.d.ts')['ZhScatterchart']
 ZhChat: typeof import('../dist/components/index.d.ts')['ZhChat']
 ZhAside: typeof import('../dist/components/index.d.ts')['ZhAside']
 ZhContainer: typeof import('../dist/components/index.d.ts')['ZhContainer']
 ZhFooter: typeof import('../dist/components/index.d.ts')['ZhFooter']
 ZhHeader: typeof import('../dist/components/index.d.ts')['ZhHeader']
 ZhMain: typeof import('../dist/components/index.d.ts')['ZhMain']
 Componentlibrary: typeof import('../dist/components/index.d.ts')['Componentlibrary']
 Designcanvas: typeof import('../dist/components/index.d.ts')['Designcanvas']
 Designertoolbar: typeof import('../dist/components/index.d.ts')['Designertoolbar']
 Exportdialog: typeof import('../dist/components/index.d.ts')['Exportdialog']
 Propertypanel: typeof import('../dist/components/index.d.ts')['Propertypanel']
 Resizehandles: typeof import('../dist/components/index.d.ts')['Resizehandles']
 Widgetrenderer: typeof import('../dist/components/index.d.ts')['Widgetrenderer']
 ZhBigscreendesigner: typeof import('../dist/components/index.d.ts')['ZhBigscreendesigner']
 Baidumapcontent: typeof import('../dist/components/index.d.ts')['Baidumapcontent']
 Barchartcontent: typeof import('../dist/components/index.d.ts')['Barchartcontent']
 Bordercontent: typeof import('../dist/components/index.d.ts')['Bordercontent']
 Buttoncontent: typeof import('../dist/components/index.d.ts')['Buttoncontent']
 Gaodemapcontent: typeof import('../dist/components/index.d.ts')['Gaodemapcontent']
 Imagecontent: typeof import('../dist/components/index.d.ts')['Imagecontent']
 Inputcontent: typeof import('../dist/components/index.d.ts')['Inputcontent']
 Layoutcontent: typeof import('../dist/components/index.d.ts')['Layoutcontent']
 Linechartcontent: typeof import('../dist/components/index.d.ts')['Linechartcontent']
 Piechartcontent: typeof import('../dist/components/index.d.ts')['Piechartcontent']
 Placeholdercontent: typeof import('../dist/components/index.d.ts')['Placeholdercontent']
 Ringchartcontent: typeof import('../dist/components/index.d.ts')['Ringchartcontent']
 Scatterchartcontent: typeof import('../dist/components/index.d.ts')['Scatterchartcontent']
 Selectcontent: typeof import('../dist/components/index.d.ts')['Selectcontent']
 Tablecontent: typeof import('../dist/components/index.d.ts')['Tablecontent']
 Tencentmapcontent: typeof import('../dist/components/index.d.ts')['Tencentmapcontent']
 Textcontent: typeof import('../dist/components/index.d.ts')['Textcontent']
 Textinputcontent: typeof import('../dist/components/index.d.ts')['Textinputcontent']
 Timepickercontent: typeof import('../dist/components/index.d.ts')['Timepickercontent']
 Videocontent: typeof import('../dist/components/index.d.ts')['Videocontent']
 ZhCeditor: typeof import('../dist/components/index.d.ts')['ZhCeditor']
 ZhEditor: typeof import('../dist/components/index.d.ts')['ZhEditor']
 ZhFileviewer: typeof import('../dist/components/index.d.ts')['ZhFileviewer']
 Circleloading: typeof import('../dist/components/index.d.ts')['Circleloading']
 Ofdpreview: typeof import('../dist/components/index.d.ts')['Ofdpreview']
 Ofdviewer: typeof import('../dist/components/index.d.ts')['Ofdviewer']
 Pageindicator: typeof import('../dist/components/index.d.ts')['Pageindicator']
 Ratioindicator: typeof import('../dist/components/index.d.ts')['Ratioindicator']
 Tooltip: typeof import('../dist/components/index.d.ts')['Tooltip']
 ZhFormItem: typeof import('../dist/components/index.d.ts')['ZhFormItem']
 ZhForm: typeof import('../dist/components/index.d.ts')['ZhForm']
 ZhHideNumber: typeof import('../dist/components/index.d.ts')['ZhHideNumber']
 ZhIcon: typeof import('../dist/components/index.d.ts')['ZhIcon']
 ZhImage: typeof import('../dist/components/index.d.ts')['ZhImage']
 ZhInput: typeof import('../dist/components/index.d.ts')['ZhInput']
 ZhAmap: typeof import('../dist/components/index.d.ts')['ZhAmap']
 ZhBmap: typeof import('../dist/components/index.d.ts')['ZhBmap']
 ZhOmap: typeof import('../dist/components/index.d.ts')['ZhOmap']
 ZhSmap: typeof import('../dist/components/index.d.ts')['ZhSmap']
 ZhTmap: typeof import('../dist/components/index.d.ts')['ZhTmap']
 ZhMediaswiper: typeof import('../dist/components/index.d.ts')['ZhMediaswiper']
 MessageIcon: typeof import('../dist/components/index.d.ts')['MessageIcon']
 ZhMessage: typeof import('../dist/components/index.d.ts')['ZhMessage']
 ZhNoData: typeof import('../dist/components/index.d.ts')['ZhNoData']
 ZhOperationcolumn: typeof import('../dist/components/index.d.ts')['ZhOperationcolumn']
 ZhAuthcontrol: typeof import('../dist/components/index.d.ts')['ZhAuthcontrol']
 ZhAuthprovider: typeof import('../dist/components/index.d.ts')['ZhAuthprovider']
 ZhQrcode: typeof import('../dist/components/index.d.ts')['ZhQrcode']
 ZhRadio: typeof import('../dist/components/index.d.ts')['ZhRadio']
 ZhSearchForm: typeof import('../dist/components/index.d.ts')['ZhSearchForm']
 ZhSignature: typeof import('../dist/components/index.d.ts')['ZhSignature']
 ZhSwitch: typeof import('../dist/components/index.d.ts')['ZhSwitch']
 ZhTable: typeof import('../dist/components/index.d.ts')['ZhTable']
 ZhPhotowall: typeof import('../dist/components/index.d.ts')['ZhPhotowall']
 ZhSign3d: typeof import('../dist/components/index.d.ts')['ZhSign3d']
 ZhTorusknot: typeof import('../dist/components/index.d.ts')['ZhTorusknot']
 ZhCupload: typeof import('../dist/components/index.d.ts')['ZhCupload']
 ZhUpload: typeof import('../dist/components/index.d.ts')['ZhUpload']
 ZhUploadcard: typeof import('../dist/components/index.d.ts')['ZhUploadcard']
 ZhUploaddialog: typeof import('../dist/components/index.d.ts')['ZhUploaddialog']
 ZhDhplayer: typeof import('../dist/components/index.d.ts')['ZhDhplayer']
 ZhHlsplayer: typeof import('../dist/components/index.d.ts')['ZhHlsplayer']
  }
}

export {}
