// 本文件由 scripts/generateIcons.ts 自动生成，请勿手动修改
import { createIcon } from '../createIcon'

export const CAirplane = createIcon('c-airplane')
export const CNoData = createIcon('c-no-data')
export const CCar = createIcon('c-car')
export const CUpload = createIcon('c-upload')
export const CPdfFill = createIcon('c-pdf-fill')
export const CDownload = createIcon('c-download')
export const CZhihui = createIcon('c-zhihui')
export const CPpt = createIcon('c-ppt')
export const CExcel = createIcon('c-excel')
export const CPdf = createIcon('c-pdf')
export const COfd = createIcon('c-ofd')
export const CDissatisfied = createIcon('c-dissatisfied')
export const CGeneral = createIcon('c-general')
export const CVerySatisfied = createIcon('c-very-satisfied')
export const CSatisfaction = createIcon('c-satisfaction')
export const CPptFill = createIcon('c-ppt-fill')
export const COfdFill = createIcon('c-ofd-fill')
export const CWordFill = createIcon('c-word-fill')
export const CExcelFill = createIcon('c-excel-fill')
